### ISSUE TITLE
AttributeError: 'module' object has no attribute 'inf_get_min_ea'

### ISSUE THREAD

**Issue by AlifeLine** [sibears/IDAGolangHelper#14]
I've tried many versions of ida pro, but I still can't import the script.
Here is the error message.：
\go_entry.py: 'module' object has no attribute 'inf_get_min_ea'
Traceback (most recent call last):
  File "C:\Program Files\IDA 7.2\python\ida_idaapi.py", line 572, in IDAPython_ExecScript
    execfile(script, g)
  File "/go_entry.py", line 15, in <module>
    GO_SETTINGS = GO_Utils.GoSettings()
  File "\GO_Utils\__init__.py", line 16, in __init__
    self.bt_obj = Utils.get_bitness(ida_ida.inf_get_min_ea())
AttributeError: 'module' object has no attribute 'inf_get_min_ea'

**Comment by AlifeLine** [comment]
I fix it
i change ida_ida.inf_get_min_ea() to idc.BeginEA()

**Comment by xuing** [comment]
> I fix it
> i change ida_ida.inf_get_min_ea() to idc.BeginEA()

It work, thanks. seem like a low version compatibility issue.

**Comment by CaledoniaProject** [comment]
Just go back to https://github.com/sibears/IDAGolangHelper/tree/b6e7907755bd57f756a157b3cd7565e7ef7a5dec and it works for IDA 7.0
