### ISSUE TITLE
How to install this plugin on IDA ?

### ISSUE THREAD

**Issue by mydockergit** [sibears/IDAGolangHelper#8]
I copied all the files under `C:\Program Files (x86)\IDA 6.95\plugins` and open IDA but I don't see the plugin.
Is there other way to install it ?

**Comment by grokeus** [comment]
Hi! This is not a plugin. You should load go_entry.py in IDA via Alt+f7

**Comment by mydockergit** [comment]
Thanks. For some reason Python wasn't installed on IDA although it was installed on Windows. Reinstalling IDA and choosing to install Python now allowed me to run Python scripts. Thanks, it is working now.

**Comment by iliul** [comment]
> Hi! This is not a plugin. You should load go_entry.py in IDA via Alt+f7

Hi @grokeus , does this script support ida 7.0 ？

**Comment by grokeus** [comment]
> > Hi! This is not a plugin. You should load go_entry.py in IDA via Alt+f7
> 
> Hi @grokeus , does this script support ida 7.0 ？

Hi @iliul , yes, this scripts should work with ida7.0

**Comment by iliul** [comment]
> > > Hi! This is not a plugin. You should load go_entry.py in IDA via Alt+f7
> > 
> > 
> > Hi @grokeus , does this script support ida 7.0 ？
> 
> Hi @iliul , yes, this scripts should work with ida7.0

Thank you!

**Comment by Godzilla912** [comment]
> Hi! This is not a plugin. You should load go_entry.py in IDA via Alt+f7

How to install pluging? 
I have classinformer.dll and i copy in to plugings folder but it not show me plz help me.
